
development:
  adapter: postgresql
  encoding: unicode
  database: finish2_development
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: finish2_test
  pool: 5
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: finish2_production
  pool: 5
  username:
  password:
